### ISSUE TITLE
Inventory Sorting Not Working on 1.16.1

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/AutomaticInventory#35] opened 2020-07-15 21:08 UTC
In my testing, inventories are not sorting themselves, but chests are. Minecraft version 1.16.1.
 
**Testing**
Sort on: https://cldup.com/9n9V02-Z2W.png
Plugin version: https://cldup.com/NnxOf4GULp.png
Sorting broken: https://cldup.com/S386fWstsG.png

**Comment by RoboMWM** [comment] 2020-07-16 00:11
inventories as in... player inventories? Because chests are inventories too.

**Comment by ghost** [comment] 2020-07-16 04:22
Update: I noticed my inventory was being sorted but **only** while opening a chest. So, the sorting is not being performed when opening the inventory.

And that's right, I mean _player inventories_ only when writing _inventory_. It's meant in the same way common speech and this plugin describe an inventory. Typing /AutoSort gives options for sorting either "inventories" or "chests" – and the former is what is causing an issue after the update to 1.16.

**Comment by RoboMWM** [comment] 2020-07-17 03:56
yea, I guess I should change the default wording BigScary used. Anyways that indicates that the InventoryCloseEvent is no longer fired for players who close their own inventory (it never fired when they opened it but did when they closed it - which is what this plugin uses to track that afaik, along with the pickup event).

Of course, another plugin may be messing around with this event, so if you can double check if it happens with just AutomaticInventory installed that'd be helpful as well.

**Comment by ghost** [comment] 2020-07-18 22:31
Okay, I just did your test loading just that one plugin, and ran the server. The result was the same in that it would not sort my player inventory without using a chest.

Also, I checked the Wiki, I didn't know chests are "inventories" on there. But I'd prefer to keep the wording the same, since people often say things like "let me check my chests it's not in my inventory" when playing the game. Though if it's customizable in the language file, it doesn't matter all that much.

**Comment by TheoRetisch1** [comment] 2020-08-01 09:25
I'm facing the same problem using Paper 1.16.1 #130 and AutomaticInventory version 2.10.1-a8f1fec.

**Comment by RoboMWM** [comment] 2020-08-01 18:14
finally had an opportunity to test, and this appears to be the case... or at least I don't see any event being fired when I close my inventory. It used to fire InventoryCloseEvent, so I guess the client just doesn't do that anymore.

**Comment by RoboMWM** [comment] 2020-08-01 18:17
Currently busy with other stuff right now but I'll try to check on this in a week, ping me here otherwise. This will require a bit of a redesign (similar to a feature request) since the old method (watching InventoryCloseEvent) simply will not work anymore. If anyone has any suggestions on when the sorting should be performed please let me know. Currently I believe it also occurs on the pickup event.

**Comment by RoboMWM** [comment] 2020-08-04 18:45
Right now the only idea I have is this, how does this sound?

**When** a player clicks in their own inventory
**And** they have no inventory open (or their own, if this is possible to discover)
**Then** start a timer of predetermined length

**Before** the timer expires
**When** a player clicks in their inventory
**Then** reset the timer

**When** the timer expires
**Then** sort the player's inventory

**Comment by TheoRetisch1** [comment] 2020-09-19 11:18
Confirmed for Paper 1.16.3 build 198.

**Comment by RoboMWM** [comment] 2020-09-19 21:15
Ah, knew I was forgetting something here, thanks.

**Comment by RoboMWM** [comment] 2020-09-20 16:50
Defaulting to 8 seconds. I could make this configurable but may be better to "adapt" if possible, but that's for a separate feature request if the need is warranted.

**Comment by TheoRetisch1** [comment] 2020-09-20 19:10
I compiled the build but it doesn't work for me? I can't figure out how to sort the inventory. How does the new mechanism work?

**Comment by RoboMWM** [comment] 2020-09-21 15:32
Should be that any time you click something in your inventory when you have only your player inventory open, it'll start a countdown of 8 seconds, which will then cause your inventory to be sorted. The Inventory stuff is a little weird so I may have gotten it wrong, but I used similar logic so idk if there's something I'm not accounting for.

**Comment by TheoRetisch1** [comment] 2020-09-21 19:08
I tested it again on a different test server, no luck. All sort feature work, but the inventory won't sort. I tried it with different permission and toggled the sorting. There are no errors, the inventory just won't sort.  maybe I made a mistake compiling the build. I will wait for a release build to try it again :)

**Comment by RoboMWM** [comment] 2020-09-21 21:33
I made a release but no I haven't had time to test since the logic should be similar... I guess the player inventory works differently...

**Comment by RoboMWM** [comment] 2020-09-25 00:29
k, used the wrong event name, fixed and tested.

**Closed as completed by RoboMWM** 2020-09-25 00:29 UTC
Labels: enhancement

**Comment by TheoRetisch1** [comment] 2020-09-27 08:05
It works, thank you very much 💯

**Comment by RoboMWM** [comment] 2020-11-21 05:17
apparently inventorycloseevent is now working again in later 1.16 releases... so I might revert this.

**Comment by TheoRetisch1** [comment] 2020-11-24 12:47
That would be cool, the old system was more intuitive :)
