### ISSUE TITLE
1.17.1 Update

### ISSUE THREAD

**Issue by itsBeaco** [MLG-Fortress/AutomaticInventory#45] opened 2021-07-13 20:19 UTC
Please note that support and feature requests is offered only to patrons at https://r.robomwm.com/patreon - the only exception is for bug reports which impact the plugin's overall functionality, subject to the plugin developer's interpretation.

The plugin is currently still working on 1.17.1, I'm just getting 1 error which is as followed: "ERROR Could not pass event BlockFertilizeEvent to AutomaticInventory v2.12.2-eab34e8" - Would it be possible to get an update to fix this, please? The plugin is awesome and I'd love to keep using it!

Kind regards,
Connor

**Comment by RoboMWM** [comment] 2021-07-14 14:49
dispenser. been fixed but I haven't had time yet to figure out automated releases yet. Ugh. I already have this in my todo. I'll get to it within the coming weeks. 

The error is just console spam, doesn't impact anything.

**Comment by RoboMWM** [comment] 2021-07-14 14:49
duplicate of #41

**Closed as completed by RoboMWM** 2021-07-14 14:49 UTC

**Comment by itsBeaco** [comment] 2021-07-14 14:52
Sorry for the duplicate issue requested, thank you for letting me know and keep doing what you're doing! Appreciate it!
