### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [MLG-Fortress/AutomaticInventory#44] opened 2021-06-21 11:32 UTC
Using 1.16.5 airplane paper fork
https://nekobin.com/fapimebezu

**Comment by RoboMWM** [comment] 2021-06-27 04:31
Did this paste expire or something? Try using gist or mclo.gs

**Comment by LucidAPs** [comment] 2021-06-27 04:35
Yeah I don't know what happened there. Here it is https://mclo.gs/7RYUXLh

**Comment by RoboMWM** [comment] 2021-06-28 20:14
duplicate of #41 

I was going to push an update via BukkitDev's API but I still haven't gotten around to doing that I guess. Ugh.

**Closed as completed by RoboMWM** 2021-06-28 20:14 UTC

**Comment by LucidAPs** [comment] 2021-07-20 06:21
Are you going to push an update for the plugin?
