### ISSUE TITLE
BlockFertilizeEvent

### ISSUE THREAD

**Issue by JavierPM87** [MLG-Fortress/AutomaticInventory#43] opened 2021-06-02 20:25 UTC
Hello

An error has appeared in the console, I leave it here in case you are interested

Greetings

https://pastebin.com/05ECmVxU

**Comment by RoboMWM** [comment] 2021-06-04 15:34
Yup this is a duplicate of #41 and has been fixed but I haven't pushed out an update yet.

**Closed as completed** 2021-06-04 15:34 UTC
Labels: duplicate
