### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by TheoRetisch1** [MLG-Fortress/AutomaticInventory#15] opened 2019-06-13 10:31 UTC
Could you please add 1.14 support. Certainly not an easy and medium-term task. But it would be very cool to have an update as soon as the version is playable :)

Error: https://pastebin.com/zLryi41g
AutomaticInventory: 2.8.5
Paper 1.14.2 - 82

**Comment by RoboMWM** [comment] 2019-06-13 14:57
I think this is a duplicate

**Comment by RoboMWM** [comment] 2019-06-13 14:58
Duplicate of #14

**Closed as completed by RoboMWM** 2019-06-13 14:58 UTC
