### ISSUE TITLE
Some chests not accessible

### ISSUE THREAD

**Issue by ghost** [MLG-Fortress/AutomaticInventory#4] opened 2019-04-15 01:58 UTC
![2019-04-14_20 56 33](https://user-images.githubusercontent.com/14188132/56103369-0fb60c00-5ef8-11e9-82a5-57e1039c1ca7.png)

**Comment by RoboMWM** [comment] 2019-04-15 18:29
Duplicate of #2, being addressed in PR #1

**Closed as completed by RoboMWM** 2019-04-15 18:29 UTC
